### ISSUE TITLE
Install fails on Catalina

### ISSUE THREAD

**Issue by nrdxp** [numtide/nix-unstable-installer#13]
**Describe the bug**

An installation attempt on our Mac CI builders running Catalina resulted in the following:
```
13>Aug 30 18:59:06 mac-mini-2-signing sudo[619]: getgroupcount called triggering group enumeration
~~> Creating a Nix volume

11>Aug 30 18:59:06 mac-mini-2-signing com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.diskutil.625): Failed to bootstrap path: path = /usr/sbin/diskutil, error = 2: No such file or directory
Error starting APFS Volume creation: Insufficient privileges (-69863)
```

I can't run the script as root to boost priviledges or it fails with the `don't run as root` error.

**To Reproduce**

1. run the installer from MacOSX Catalina
2. be greeted with the above error? (not sure how reproducible the issue is, but it's coming from a fresh installation of Catalina)

**Expected behavior**

Nix should install, as the stable installer still works.

**Additional context**

I tried both with and without `darwin-use-unencrypted-nix-store-volume` and get the same error. After looking at the install script, it says this option is no longer required and it doesn't seem to do anything anymore. Is the inclusing of the volume script autodetected now perhaps?

**Comment by lilyinstarlight** [comment]
The create-darwin-volume.sh script seems to have been mostly rewritten in NixOS/nix#4289, which may be the cause for the difference in behavior between Nix stable and unstable in your CI.

I added a macOS test for this repo in #14, but the run I did installed and ran just fine. (Using install-nix-action, it ran the install with the flags `--daemon --daemon-user-count 4 --no-channel-add --darwin-use-unencrypted-nix-store-volume --nix-extra-conf-file /tmp/nix.conf`)

As a temporary test, can you try your CI using https://nixos-nix-install-tests.cachix.org/serve/v936a7w28x1zlv6qh2hc17sbfqf30zj5/install as the install script?

**Comment by nrdxp** [comment]
@lilyinstarlight, your script failed with a sha mismatch pretty early on so I don't think it even tried to make the volume from what I could gather in the logs.

**Comment by lilyinstarlight** [comment]
Oh yeah you have to add `--tarball-url-prefix https://nixos-nix-install-tests.cachix.org/serve` when running that script (I'd forgetten that when I hastily grabbed the link). I was mostly curious if that script also failed because if so, your problem may be better reported to the Nix repo rather than this one (since this repo just pulls the builds from Hydra and rewrites the base URL)

**Comment by nrdxp** [comment]
well it failed again with the same error, but two different hashes :confused:

**Comment by zimbatm** [comment]
This looks like an upstream issue to me. This project just pulls and publishes the tarballs from Hydra. The only difference is that it changes the URL to fetch the tarballs in the installation script.

**Comment by nrdxp** [comment]
closing and reported upstream:
https://github.com/NixOS/nix/issues/4994#issuecomment-909371702
