### ISSUE TITLE
How to enable flakes by default?

### ISSUE THREAD

**Issue by rigille** [numtide/nix-unstable-installer#15]
Hey I would like to use nix to manage dependencies in a project I work on and I searching for a way to install nix with flakes enabled in a single command. When I ran the installer (macOS 11.2.3) I didn't get experimental features enabled. Is there a flag that would enable them by default?

**Comment by zimbatm** [comment]
That's more a question for upstream. There is: `--nix-extra-conf-file`: Path to nix.conf to prepend when installing /etc/nix/nix.conf

**Comment by zimbatm** [comment]
According to #20, flakes are now enabled by default

**Comment by lilyinstarlight** [comment]
To clarify a bit further, https://github.com/cachix/install-nix-action (for GitHub Actions) has enabled flakes by default now. If you are using the installer here outside of GitHub Actions or without cachix/install-nix-action, you'll still need to supply the `--nix-extra-conf-file` option like @zimbatm noted above
