### ISSUE TITLE
Also publish the Docker images

### ISSUE THREAD

**Issue by zimbatm** [numtide/nix-unstable-installer#32]
**Is your feature request related to a problem? Please describe.**

I noticed that Hydra now also builds and publishes docker images:
![image](https://user-images.githubusercontent.com/3248/180782134-36c177a2-b68f-49cb-a872-3fbfe0d8dbfb.png)

It would be nice if those where accessible somehow.

**Describe the solution you'd like**

Publish those to the GitHub Package registry.

**Describe alternatives you've considered**

Docker Hub?

**Additional context**

See https://hydra.nixos.org/eval/1772518

**Comment by lilyinstarlight** [comment]
This would be pretty sweet! Do you think the images should additionally be added as a download on the release page or no?

Either way it would probably be good to add the ghcr.io URLs to both the release page and README.md.erb

**Comment by zimbatm** [comment]
Might as well? I was concerned about limits, but it looks like we're in the green:

> We don't limit the total size of the binary files in the release or the bandwidth used to deliver them. However, each individual file must be smaller than 2 GB.

source: https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#distributing-large-binaries
