### ISSUE TITLE
Attach the usage instructions to the release

### ISSUE THREAD

**Issue by zimbatm** [numtide/nix-unstable-installer#36]
**Is your feature request related to a problem? Please describe.**

Pushing README.md updates to master is creating noise in the git history.

**Describe the solution you'd like**

This hit me yesterday; instead of rendering and updating the README.md, why not attach the usage instructions as release notes?

That way, the instructions can be adapted to the release and change over time.

**Describe alternatives you've considered**

Keep things as they are

**Additional context**

**Comment by lilyinstarlight** [comment]
We could probably do that to reduce noise. Right now each tag has a distinct commit, so would you just want it to keep retagging whatever is the top commit instead?

**Comment by zimbatm** [comment]
Ah yes, I didn't think about that. It makes sense to me to advertise which version of the code generated the release. Is it possible to create multiple releases with the same tag?
