### ISSUE TITLE
add experimental features by default

### ISSUE THREAD

**Issue by nrdxp** [numtide/nix-unstable-installer#9]
Would it be simple enough to edit the bundled nix.conf to add the necessary `experimental-features` by default?

**Comment by zimbatm** [comment]
That's handled in the second layer of install scripts that are packed with the tarballs.

I think you can already achieve that by passing the `--nix-extra-conf-file <PATH>` option to the installer. The install-nix-action also has a `with_config` option (if you're using GHA).
